services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'toor'
      MYSQL_DATABASE: 'credito-individual'
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db_data: